### ISSUE TITLE
Inserter - cursor not following along focus when inserting a new block

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#113]
Coming from https://github.com/wordpress-mobile/gutenberg-mobile/pull/105#pullrequestreview-145980349

> If I'm editing a text block and I add another, the "focus" switches to the newly inserted block, but the cursor stays in the previous block. I'm not sure if we're worrying about that at this point, but leaving a note here.

~**ToDo:**~
- [x] ~#237 handle focus on RichText-based blocks~
- [x] ~#250 handle focus on other blocks~

**EDIT: 
ToDo:**
Recreating the ToDo list here after [migration to FlatList](https://github.com/wordpress-mobile/gutenberg-mobile/pull/256#pullrequestreview-177652478) 
- [ ] handle focus on RichText-based blocks
- [x] #250 handle focus on PlainText-based blocks

**Comment by mzorz** [comment]
Thanks for the heads up @daniloercoli - tested and verified this is the case. Reopening 😞

**Comment by mzorz** [comment]
Confirming it works on InputText-based blocks with FlatList (Gutenberg's PlainText primitive)
