### ISSUE TITLE
Design Audit – June 2019

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1163]
It's time for another round of audit on the current state of Mobile Gutenberg. We've made substantial progress in the past couple of months, so most of this is new, but there are a few things that are left-over from the last round or have been delegated to the future.

**Note: this is an in-progress master issue. I will be creating/finding separate issues for each item and linking to those from this master issue.**

This list is broken down into categories based on focus area, with a bias towards UI polish and writing flow of _existing things_. I will try to order based on approximate importance in terms of user impact. Each issue will need to be prioritized separately in the [main project board](https://github.com/wordpress-mobile/gutenberg-mobile/projects/1).

### All Blocks
- [x] Selected blocks no longer have left/right borders on wide viewports #1193 
- [x] Remove extra inner padding on text blocks #992
- [x] (follow up to the above ^ one) Remove extra padding on Post Title #2021
- [x] It's too easy to accidentally delete blocks #1146
- [ ] [Android] Ensure Noto-Serif is properly applied to Headings #1147
- [x] Refine border-radii on placeholder/unsupported blocks #999

### Bottom Sheets
- [x] Tapping "return" should dismiss sheet #1164
- [ ] Improve text entry for long text in the image settings bottom sheet #922 (this should be approached from a Sheets/input component view)

### Quick Toolbar
- [x] Remove border-left from Quick Toolbar #639

### Inserter
- [x] "Add New Block" indicator isn't shown when title field is focused #632
- [x] "Add new block" indicator should show in place of empty block instead of below it #1165 / #1177 
- [x] Refine "Add new block" indicator style #1166
- [ ] Allow only 1 read-more block per post #1156 
- [x] Order blocks based on usage stats or content type #1105

### RichText Blocks

- [ ] Add underline option to text-based blocks: https://github.com/wordpress-mobile/gutenberg-mobile/issues/562

### Image block
- [x] Add visual emphasis to focused images #601 (this was done to Video recently)
- [x] Add description/title to Image selection sheets #986
- [ ] Add GIF badge to GIFs in editor #968
- [ ] Simplify media insertion flow #946
- [ ] Bring additional image settings into Image block

### Video block
- [ ] [iOS] Videos added from media library don't load in the editor #1151
- [x] Clean up video block styling #1178 

### Quote block
- [x] Can't hide keyboard reliably on Quote block #1103
- [ ] ~[Quote] Tapping return at end of block doesn't create new block #1104~

### List block
- [x] Additional Empty line added when adding items #954

### Page Break Block

- [x] Refine Page Break Block designs: https://github.com/wordpress-mobile/gutenberg-mobile/issues/618

### Separator block
- [ ] Line should be styled to match designs (https://cloudup.com/ctkvab1tgA5)

### Misc

- [x] iOS - Display word, character count on overflow menu Action Sheet #506 

### Unsupported Blocks

- [ ] (Mostly Done) Update design for Unsupported blocks: https://github.com/wordpress-mobile/gutenberg-mobile/issues/479

### Next/Future
- [x] Add additional sources to Image block #720 
- [ ] Allow easier setting of Featured Image #1011
- [ ] Proposal: Add search to Inserter
- [ ] Try: Quick action gestures #1040
- [ ] Proposal: New "default" Quick Toolbar #1020 
- [ ] Try: Make Quick Toolbar styles feel more platform-specific #695
- [ ] Proposal: Collapse/expand top bar on scroll #614
- [ ] Future proposal: Add Justify options where text-alignments are supported: https://github.com/wordpress-mobile/gutenberg-mobile/issues/575
- [ ] ~Improve base typographic rhythm: https://github.com/wordpress-mobile/gutenberg-mobile/issues/550~ Will be updated with an upcoming new type scale
- [ ] [Try] Improve editor loading experience #1179

### Design Notes
- [ ] ~Should we switch to 16px padding on all dividers on sheets for consistency?~

There are more issues that I've excluded from this list because they either aren't high priority at the moment, or are way off in the future. https://github.com/wordpress-mobile/gutenberg-mobile/issues/created_by/iamthomasbishop

**Comment by kyleaparker** [comment]
Closing in favour of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2656
