### ISSUE TITLE
Synch mobile editor preferences: Master issue

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#1233]
This master ticket explains the editor preference synch scenarios for release v13.0 of mobile apps.

The plans for v13.0 is to have the apps fully synching the editor preferences with the backend, and use this info when launching the editor for NEW post, and display the right editor for each site.
(The wpcom API has been enhanced with an endpoint /sites/:site/gutenberg that gives us information on whether the user has opted in/out for Gutenberg on the web and mobile for a specific site (the granularity for opt-in is per-user/per-site). We will use this information to understand which editor to show on NEW post.)

Self hosted sites will use the local setting, stored in site-settings.

### When to synch with the backend

- App comes from background (maybe throttled every n times), so we can have the freshest value each time
- When the user switches to another site in the app (given the information is per-user/per-site). 

### Preference migration strategy from 12.9 to 13.0
**_WPCOM_** : The app will call the `editor` endpoint and read from the backend
When the call finishes, the app does check the `mobile` value, and if it’s `null` or empty string the app will set the `mobile` preference (both local and remote) with what’s stored in the global app preference used in 12.9
**_ORG_**: Just store the global app value to site settings. Nothing is going to be synched with the remote site.

### New installation (users that don't have seen the prompt about the new editor on mobile)
- The API will return null and we have `null` in the local app DB
- Once opening a GB post, we know that the value is null, make the flip, show the dialog, and save to remote.

### What editor to show on new post ?
Just check the value of the editor setting.

If the synch with the remote didn’t happen yet for some reason, use the local app setting.

### New mobile users
New signups from mobile will get GB enable on mobile. 

Ideally we would have the backend setting the mobile editor setting to gutenberg for new users. In that way, we get the default to gutenberg centralized, managed by the API.
Otherwise we need to make an API call right after the signup.

### Tasks

- [x] Update the REST API and make it return empty string for users that didn’t set the mobile preference yet
- [x] Move the UI toggle from App Settings to Site Settings
- [x] Sync from the API by following the migration strategy and populate the site setting. 
- [x] Display the right editor for each site
- [x] Save to the API when the editor preference is changed by the user (via site settings and the editor)

**Comment by etoledom** [comment]
I'd say this is done, @daniloercoli ?

**Comment by daniloercoli** [comment]
Address in the PRs linked above.
