### ISSUE TITLE
Image Block

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#140]
This is a master issue for implementing the Image Block.

This block has many different features, and the plan is to implement them one by one.

- [x] Recognize the image block (To not show the unsupported message) (#141)
- [x] Recognize an empty image block and an image block with content. (#143)
- [x] Show basic UI to add an image on an empty image block. (#143)
- [x] Show an image. (Not sure yet if the host app should manage the downloads). (#143)

Block settings:
- [ ] Image dimensions (width, hight) (#147)
- [x] Caption (#161)
- [ ] ALT text
- [ ] Image size (Thumbnail, medium, etc...)
- [ ] Link to.
- [ ] Link URL

**Comment by koke** [comment]
I think all the remaining items are being tracked in #202, closing this one
