### ISSUE TITLE
Media & Text block design review

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1476]
As we get ready to ship the first version of the Media & Text block to production, I wanted to take some time to point out some issues I found while doing a design review. This issue is meant to act as a master issue, but feel free to break into separate issues.

@pinarol @hypest would you be able to triage these? I'm not sure who should work on each of these. I wanted to document so we aren't losing the points somewhere.

- [x] Alignment options not working ([existing issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1312))
- [x] Paragraph block has additional left/right padding ([example](https://cloudup.com/c-5W6z27BKM) – related to InnerBlocks work?)
- [x] Change paragrph placeholder text label to "Start writing..." to match other placeholder labels
- [ ] When media block has media, we should add a blue highlight/border on media ([related](https://github.com/wordpress-mobile/gutenberg-mobile/issues/601)) – this would be solved by the following issue ⬇️ 
- [ ] Allow media within media & text block to be selected ([issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1607))
- [x] "Add new block here" indicator not showing inside non-media side when using Inserter ([example](https://cloudup.com/cSWVCmFskFR))
- [x] Icon for "replace media" should be updated to use updated icon (being used in updated Image block toolbar)

Fixed by InnerBlocks work? // cc @pinarol 

- Selection highlighting, parent/child relationships aren't clear
- Add floating toolbar UI to help with nesting navigation

-------

Note: all tested on WPiOS 13.5. iOS 13.1.3 on iPhone 11 Pro, and iPadOS 13.2b3 on iPad Pro 10.5".

**Comment by pinarol** [comment]
I am expecting that these will be fixed by the ongoing InnerBlocks work:

Paragraph block has additional left/right padding
Selection highlighting, parent/child relationships aren't clear
Add floating toolbar UI to help with nesting navigation

**Comment by iamthomasbishop** [comment]
Updated the original tasks to reflect the current progress, and added an [additional issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1607).

**Comment by geriux** [comment]
> Paragraph block has additional left/right padding (example – related to InnerBlocks work?)

Checked this item of the list since it is properly aligned now:

<img width="412" alt="Screenshot 2020-03-12 at 18 12 36" src="https://user-images.githubusercontent.com/4885740/76547303-3cb6ca00-648d-11ea-8e82-d2f1c617dd19.png">

**Comment by geriux** [comment]
> Icon for "replace media" should be updated to use updated icon (being used in updated Image block toolbar)

I've checked this one too since I merged the icon [PR](https://github.com/WordPress/gutenberg/pull/20841):

<img width="326" alt="Screenshot 2020-03-13 at 13 58 44" src="https://user-images.githubusercontent.com/4885740/76623090-0fbcf280-6533-11ea-9216-36a9665ea785.png">

**Comment by geriux** [comment]
Regarding: 

> - When media block has media, we should add a blue highlight/border on media (related) – this would be solved by the following issue ⬇️
> - Allow media within media & text block to be selected (issue)

I think those could be handled in [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1607).

Maybe this one could be closed since the rest of the items are done and continue working on the other one.

**Comment by pinarol** [comment]
Closing this in favor of [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1607) as that's the only one left in the list.
