### ISSUE TITLE
Block split and merge

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#167]
When a user presses return the block should split in two at the cursor. Similarly, backspace at the beginning of a block should merge it with the previous block (or _forward delete_ at the end of a block)

There are some extra rules for this so double check what Gutenberg does and follow the same patterns. I don't think we have to worry about many of those yet since we only support a few block types, but one that I've identified so far is:

- When you press return, the newly created block will be a paragraph, unless it's a multiline block (I think we only have `code` in the alpha).

- [x] Merge the content (or return false to let Aztec native to handle the backspace)
- [x] Merge 2 blocks of different types
- [x] Resize after block splitting
- [x] Fix problem with content lost on merging
- [x] Fix delayed updated from native side (not completely related to this feature, but we need it)
- [ ] Focus is moved to the wrong block after merging/splitting (We may need to wait until focus problems are resolved)
- [ ] ~On blocks merging, should we add a white space character before the content of the 2nd block? (if necessary). Otherwise there is a situation where the last word of the first block, and the first word of the 2nd block, are merged together firing up the spell checker inline suggestions.~
- [x] ~Test on RTL languages~ #380
- [x] Block Splitting:  If `before` content is omitted, treat as intent to delete block and call `onReplace( [] );`
- [x] Check `Code` block in regard to enter and backspace

- [x] Using backspace while the first word is highlighted should not merge the 2 blocks, only remove the currently selected word. It's working as expected on Android, but iOS does merge the 2 blocks. #325

- [ ] Add Enter.key handling/detection to PlainText and PlainText powered blocks #324

**Comment by diegoreymendez** [comment]
Issues remaining (at least in iOS):

1. @danilo and @hypest [reported a problem](
https://github.com/wordpress-mobile/react-native-aztec/pull/62#issuecomment-431324688) with the text at the right position of the caret not being removed from the original block.
2. Blocks are not resizing correctly after being split.
3. The iOS native caret position should be compatible with unicode characters.  This is especially important for languages such as Japanese and Chinese.

**Comment by koke** [comment]
@daniloercoli @diegoreymendez since you're already working on this, can you make a task list of what needs to be done and add some estimations by Wednesday?

> The iOS native caret position should be compatible with unicode characters. This is especially important for languages such as Japanese and Chinese

Is this not working now? How is it behaving?

**Comment by koke** [comment]
Also, I initially put this in #168 but take into account as well updating the Heading (and any other ported) block so it works correctly

**Comment by diegoreymendez** [comment]
> Is this not working now? How is it behaving?

It's a pending task.  It'll require some changes in iOS for sure, but they should be fairly simple.

**Comment by daniloercoli** [comment]
- [ ] Intercept del BackSpace or delete on Android Aztec /iOS Aztec
- [ ] Write the BackSpace listener for both platforms in Aztec Wrapper. Emit the JS event
- [ ] Merge the content (or return false to let Aztec native to handle the backspace)
- [ ] Resize after block splitting
- [ ] Check Code block

**Comment by koke** [comment]
> On blocks merging, should we add a white space character before the content of the 2nd block? (if necessary). Otherwise there is a situation where the last word of the first block, and the first word of the 2nd block, are merged together firing up the spell checker inline suggestions.

I'd say that's the expected behavior and how any other editor does it, no need to worry about that

**Comment by Tug** [comment]
Not sure it has already been mentioned but here is an extra edge-case/bug to fix:
- [ ] Using backspace while the first word is highlighted should not merge the 2 blocks, only remove the currently selected word

**Comment by koke** [comment]
I did a quick test on RTL (Arabic keyboard), enter and backspace seem to split/merge fine, although the splitted blocks get the wrong alignment

**Comment by koke** [comment]
Moved RTL testing to the beta in #380, since we can use some help with that

**Comment by koke** [comment]
I'm going to close this, since there are only two things in the list:

- Focus is moved to the wrong block after merging/splitting (We may need to wait until focus problems are resolved). @daniloercoli I believe this is fixed already
- Add Enter.key handling/detection to PlainText and PlainText powered blocks. Already tracked in #324, and we might postpone for beta
