### ISSUE TITLE
Design Audit - Nov/Dec 2019

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1671]
It's time for another round of audit on the current state of Mobile Gutenberg! This time around, @SylvesterWilmott offered to take GB for a spin with fresh eyes. He kindly documented some of the things that stood out to him – some of which were known issues, some not. I'm going to create new issues this afternoon to document the things that aren't already on our radar.

Note: there are still some things from the last design audit ([Master Issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1163)) that haven't been addressed, so we should also reference those now that we're beyond some of the more immediate v2 shipments.

Note: this is an in-progress master issue. We will be creating/finding separate issues for each item and linking to those from this master issue.

## Bugs

- [ ] Scroll canvas to new block when one is added (#1672)
- [x] Quote border-left not visible in dark mode (#1673)
- [ ] When typing into a right aligned input in block settings (ie img alt text) spaces are not shown as you enter them (#2053)

## Improvements

- [ ] [iOS] Consider changing “keep editing” label on `•••` menu action sheet to “cancel” or “dismiss”
- [ ] Consider showing a “done” bar/button when a URL input (any text input?) is focused
- [ ] [Try] Refine link editing flow while cursor is next to link (#2054)

## Needs Design Exploration

- [ ] Consider alternative treatments for Quote text
- [ ] Add smooth transitions when blocks are moved
- [ ] Consider giving all selected blocks strong outline, similar to InnerBlocks

**Comment by kyleaparker** [comment]
Closing in favour of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2656
