### ISSUE TITLE
Focus management

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#196]
Creating this issue to group a few bugs related to focus that we want to address for the alpha:

- [x] Tapping into RichText doesn't move the cursor properly on Android #135
- [x] Inserting a new block doesn't make cursor immediately available on new block #113, #270 
I think these two were estimated at 2 weeks
- [x] ~Tapping into PlainText doesn't allow to select text / copy / paste #267~ doesn't apply as we [move on using FlatList ](https://github.com/wordpress-mobile/react-native-recyclerview-list/pull/11)

Parting the case into more granular items here:
- [x] Tapping into PlainText doesn't make the block-holder selected #251
- [x] ~Implement InputTextState-like focus sync for Aztec #273~
- [x] Tapping into a block doesn't make the block selected #287
- [x] RichText: when the caret is blinking, tapping on any inline toolbar action button (down/up, trash) does not work and instead makes the next available editable to get the focus #292 
- [x] RichText: when toolbar is actionable (note it's different than being just shown), can't obtain focus on editable  #293 
- [x] Focus Loop when deleting content and blocks #302 
- [x] Pressing delete at the beginning of a block (and NO merge) moves the focus to the wrong block #306 (closed without fixig it for the alpha, but opened a new issue for the beta phase).
- [ ] Tapping on a Page Break block does make the block-holder selected but keep the keyboard up, and the caret to the Para block #308
- [ ] https://github.com/wordpress-mobile/WordPress-Android/pull/8800 [Android only] [Preserve scroll and caret position after rotating](https://github.com/wordpress-mobile/WordPress-Android/issues/8739) (Gutenberg Editor)

**Comment by koke** [comment]
I'm going to close this one, since #308 is about to land in master, and the rotation issues will be handled in the beta
