### ISSUE TITLE
Keyboard management

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#197]
There are some issues related to keyboard, keeping track of them here:

- [ ] When a block is selected, ensure the cursor is visible, scrolling the list if necessary.
- [x] #308 When a non textual block (e.g. image, more) is selected, hide the keyboard.
- [x] #291 when keyboard is up and user taps on another RichText component, keyboard is dismissed
- [ ] #381 keyboard gets dismissed when a new block is created tapping `Enter`. (keyboard should stay open to let the user continue typing)

This is related to #196 and the keyboard tasks in #55 

~I think 2 weeks should be enough but it needs further analysis.~

**Comment by koke** [comment]
I took a first stab at scrolling to a newly created block in e663cbf928214ee019a6cc8cbdfd9fa89e62ce11, but that will try to scroll every time the selection changes. It seems like we'd need to keep track of which items are visible via `onViewableItemsChanged` and only scroll if the desired item isn't visible.
