### ISSUE TITLE
List block

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#208]
Add support for the `list` block.

I don't know the difficulty of implementing the indent and outdent buttons, but I'd be fine leaving those out of the beta. I don't see anything else on the web version to leave out.

List-related issues:

- [x] Editor crash when undoing at list end #836
- [x] List crashes with extra spaces #871
- [x] List block split: item and caret at wrong lines when nested lists #886
- [ ] List block split problem with nested lists #874

Not blockers:

- [ ] List Block Ordered list number indicators don't respect alignment #846

**Comment by koke** [comment]
This was estimated at 1-2 weeks by @daniloercoli, but as @diegoreymendez pointed out, we were not accounting for nested lists. Hopefully those are easy, but they aren't as critical for the beta, so we'll count *2 weeks per platform* for this task and re-evaluate when we know more

**Comment by hypest** [comment]
Known issues after https://github.com/wordpress-mobile/gutenberg-mobile/pull/704:

### caret positioning when new item at the end
1. Do a long list, long enough to have a few empty list items here and there
2. Try to add a new item at the end of the list
3. Notice that the caret doesn't land on the new list item but rather, goes "back". The more empty lines from 2., the more chars the caret goes back.

**Comment by koke** [comment]
Let's keep this open until we have nested lists, and the implementation is solid enough to enable on production builds.

**Comment by koke** [comment]
To avoid cluttering the 2.0 Bugs column, I started a checklist on this issue with all the list-related bugs. Please keep adding there as you find them. When this is ready for production, let's make sure any remaining items have a card in the project

**Comment by iamthomasbishop** [comment]
Just added my notes from a quick design review on the current (as of the current alpha) list block: https://github.com/wordpress-mobile/gutenberg-mobile/issues/897

**Comment by mchowning** [comment]
Added a minor issue related to caret positioning when splitting list items: #929

**Comment by hypest** [comment]
Bumping this to the next milestone.

**Comment by koke** [comment]
Since we're shipping lists for both platforms in 1.4, and we have individual issues for every known bug, I think we can close this one?

**Comment by hypest** [comment]
Will strikethrough the non-checked items in the ticket and will leave the individual tickets to have a life of their own 👍 .
