### ISSUE TITLE
Unsupported blocks fallback mechanism

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#2358]
### Description

Implement a fallback mechanism for unsupported blocks. A user who encounters an unsupported blocks should be able to view and edit the block in question, without leaving the mobile Gutenberg editor.

### Subtasks
- [ ] Enable unsupported block editing on dev builds
   - [x] [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/21150)
   - [x] [Gutenberg Mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2063)
   - [x] [Android PR](https://github.com/wordpress-mobile/WordPress-Android/pull/11919)
   - [ ] [iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/13967)
   - [ ] [UI tests PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2345)
- [ ] Fix [support for Atomic sites](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2063#issuecomment-638471473)
- [ ] Fix [the `\n` issue](https://github.com/wordpress-mobile/WordPress-Android/pull/11919#issuecomment-638473388)

**Comment by etoledom** [comment]
We are finishing the focus on this feature after merging the main PRs (https://github.com/WordPress/gutenberg/pull/21150 https://github.com/WordPress/gutenberg/pull/25238) and the most important side PRs described on this ticket.

What's left will be worked later on after new assignments are made.
