### ISSUE TITLE
[WIP] Design Audit - September 2020

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/gutenberg-mobile#2656]
It's time for another round of audit on the current state of Mobile Gutenberg! 

Note: there were still some things from the last two design audits that haven't been addressed (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1671) (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1163), I will be closing those issues and moving everything over to this updated issue.

Note: this is an in-progress issue. We will be creating/finding separate issues for each item and linking to those from this issue.

## Bugs

- [x] [Android] Remove press action on sliders https://github.com/wordpress-mobile/gutenberg-mobile/issues/2633
- [x] [Android] Align the slider to the left https://github.com/wordpress-mobile/gutenberg-mobile/issues/2667
- [x] Pluralize "Choose Image" heading on Gallery Block #2632 
- [ ] ~~Activate the link button at the end of a string #2631~~
- [x] Button settings inaccessible when block first added https://github.com/wordpress-mobile/gutenberg-mobile/issues/2657
- [ ] Localisation of "Color" in button color settings https://github.com/wordpress-mobile/gutenberg-mobile/issues/2669

**Outstanding from the last reviews** (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1671) (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1163)
- [ ] Scroll canvas to new block when one is added #1672
- [ ] When typing into a right aligned input in block settings (ie img alt text) spaces are not shown as you enter them #2053
- [ ] [Android] Ensure Noto-Serif is properly applied to Headings #1147
- [x] Allow only 1 read-more block per post #1156
- [ ] [iOS] Videos added from media library don't load in the editor #1151

## Improvements

- [ ] Consistent image size selector https://github.com/wordpress-mobile/gutenberg-mobile/issues/2668

**Outstanding from the last review** (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1671) (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1163)
 - [ ] [iOS] Consider changing “keep editing” label on ••• menu action sheet to “cancel” or “dismiss”
 - [ ] Consider showing a “done” bar/button when a URL input (any text input?) is focused
 - [ ] [Try] Refine link editing flow while cursor is next to link #2054
- [ ] Improve text entry for long text in the image settings bottom sheet #922 (this should be approached from a Sheets/input component view)
- [ ] Add GIF badge to GIFs in editor #968
- [ ] Simplify media insertion flow #946
- [ ] Allow easier setting of Featured Image #1011

## Needs Design Exploration 

- [ ] Define guidelines for block settings ([example](https://take.ms/leCRt))
- [ ] Explore including a clear "Done" action when editing block settings
- [ ] Test: Full page block selector sheet (it's currently only half the height of the screen) 
- [ ] Explore adding block descriptions to each block's main settings sheet
- [ ] Test the usability of the nested block toolbar and move towards a consistent positioning on iOS and Android
- [ ] Try: Altering the blue outline on text blocks to better define the input tap target ([example of the current target](https://cloudup.com/cwZukqSU4iL)) 

**Outstanding from the last reviews** (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1671) (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1163)

- [ ] Consider alternative treatments for Quote text
- [ ] Add smooth transitions when blocks are moved
- [ ] Consider giving all selected blocks strong outline, similar to InnerBlocks
- [ ] Try: Quick action gestures #1040
- [ ] Proposal: Add search to Inserter
- [ ] Proposal: New "default" Quick Toolbar #1020
- [ ] Try: Make Quick Toolbar styles feel more platform-specific #695
- [ ] Proposal: Collapse/expand top bar on scroll #614
- [ ] Future proposal: Add Justify options where text-alignments are supported #575 

@iamthomasbishop

**Comment by SiobhyB** [comment]
Going ahead to close now that a number of years, which have included UI iterations, have passed. As most of the items from the audit had their own dedicated GitHub issue, I think we can rely on them being captured separately and/or important issues having been surfaced outside of this ticket.
