### ISSUE TITLE
Project issue: Reusable blocks

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3005]
# Description 

Epic issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2497

[Reusable blocks](https://en.support.wordpress.com/wordpress-editor/blocks/reusable-block/) allow users to quickly re-use blocks, without needing to remember specific formatting or settings. This type of blocks are currently unsupported in the app so it would be nice to add them.

# Testing builds

- iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16343
- Android: https://github.com/wordpress-mobile/WordPress-Android/pull/14500

# Phase 1

**Status:** Finished 🟢, will be released in `1.54.0 (17.5)`.

⚠️ For now, reusable block will only be available on WP.com sites due to this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/3457 ⚠️ 

## Bugs

- [ ] [Handle empty content case](https://github.com/WordPress/gutenberg/issues/32058)

### 1- Preview content

**Status:** Merged 🟢 (included in `1.46.0 (16.7)`).
<details><summary>Details</summary>

**PRs:**
- [x] [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/25265)
- [x] [Gutengerg-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2953)

**Bugs:**
- [x] [Visual glitch when loading the block](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2976) - [Fix PR](https://github.com/WordPress/gutenberg/pull/30838)

</details>

### 2 - Convert to regular blocks

**Status:** Merged 🟢 (included in `1.52.0 (17.3)`).

<details><summary>Details</summary>

**PRs:**
- [x] [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/31012)
- [x] [Gutengerg-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3397)

</details>

### 3 - Insert from the inserter menu

**Status:** Merged 🟢 (included in `1.53.0 (17.4)`).

<details><summary>Details</summary>

**PRs:**
- [x] [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/28495)
- [x] [Gutengerg-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3054)

**Subtasks:**
- [x] [Add header prop to bottom-sheet component](https://github.com/WordPress/gutenberg/pull/30291)
- [x] [Render `InserterSearchForm` in the bottom-sheet's header](https://github.com/WordPress/gutenberg/pull/30291)
- [x] [Add tabs for regular blocks and reusable blocks](https://github.com/WordPress/gutenberg/pull/28495)
- [x] [Integrate tabs into the inserter menu](https://github.com/WordPress/gutenberg/pull/28495)

**Bugs:**
- [x] [Height of the bottom-sheet changes when the keyboard is shown/hide resulting in a visual glitch](https://github.com/WordPress/gutenberg/issues/31151)
- [x] [Preserve the scroll-position on inserter menu tabs](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2689)
- [x] [Android crash when fetching more than 27 reusable blocks](https://github.com/WordPress/gutenberg/issues/29928)

</details>

# Phase 2

**Status:** In progress 🔧 .

**Bugs:**
- [ ] [Unbounded queries](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2661)
- [ ] [Bad response when a reusable block contains a self-reference on self-hosted sites](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3457)

### 1 - Edit Reusable block

**Status:** In progress 🔧

**Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2597

**Integration PRs:**
- [ ] Gutenberg PR (no created yet)
- [ ] Gutengerg-mobile PR (not created yet)

**Subtasks:**
- [ ] Floating toolbar buttons
  - [ ] [Add a slot to the floating toolbar](https://github.com/WordPress/gutenberg/pull/30302)
  - [ ] Add floating toolbar buttons in reusable block (Edit, Discard, Save)
  - [ ] [Remove floating toolbar navigation breadcrumbs](https://github.com/WordPress/gutenberg/pull/30304)
- [ ] Reusable block data management
  - [ ] Fetch reusable block data
  - [ ] Save reusable block data
- [ ] Add edit mode logic
  - [ ] Add edit name setting
  - [ ] Add unsaved changes dialog
  - [ ] Implement undo/redo functionality
  - [ ] Add focus mode and enable it when editing a reusable block
  - [ ] Add border to the parent of the inner blocks when editing (`rnmobile/add/inner-blocks-parent-border`)
- [ ] Handle editing scenarios
  - [ ] Disable editing for reusable blocks nested in another reusable block
  - [x] Render error message when the reusable block is deleted
  - [x] Render error message when rendering a reusable block nested in the same reusable block

### 2 - Save reusable block data - Support POST requests

Status: In progress 🔧

**Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/3185

**Integration PRs:**
- [ ] https://github.com/wordpress-mobile/gutenberg-mobile/pull/3128
- [ ] https://github.com/WordPress/gutenberg/pull/28938

**PRs:**
- [ ] iOS implementation
  - [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/15864
  - [ ] https://github.com/wordpress-mobile/WordPressKit-iOS/pull/349
- [ ] Android implementation

### 3- Create new Reusable block from a single block

**Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2574

# Phase 3

**Status:** Not scheduled yet.

### 1 - Manage existing Reusable blocks

**Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2598

**Comment by fluiddot** [comment]
Closing this project issue as it has been stale for a long time. Feel free to re-open it in the future when implementing the next phases of the Reusable block.
