### ISSUE TITLE
Jetpack Tiled Gallery: Square layout aspect ratio

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4010]
When images are added to the Jetpack Tiled Gallery (and the square layout is selected *), display them as squares, similar how they're displayed on the web. 

Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/3874

* At time of writing, the inner block implementation has just been merged (see https://github.com/wordpress-mobile/gutenberg-mobile/issues/4000), and we're only focusing on the square layout, so this issue is specific to the square layout.

# Tasks 

## Gutenberg changes

In order to be able to set the image block's aspect ratio via a parent block, the following changes are first necessary in Gutenberg:

- [x] Enable third-party styles to be passed to the image block's `shapeStyle` prop. Resolved in https://github.com/WordPress/gutenberg/pull/35420.
- [x] Resolve conflict with the core gallery block. The gallery block is currently forcing a fixed height for any parent blocks using a context, which will prevent parent blocks from setting custom styles. Resolved in https://github.com/WordPress/gutenberg/pull/36013.

## Aspect ratio

When the above Gutenberg changes have been shipped, it'll be possible for any parent block to set the image block's aspect ratio:

- [x] Set aspect ratio via Tiled Gallery block. Pending review in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4017.

**Comment by guarani** [comment]
👋 Hi @SiobhyB, I just realized this is assigned to me but based on your work in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4017, I changed the assignment to you. Please let me know if you think otherwise 👍
