### ISSUE TITLE
Release checklist for v1.66.0 (scheduled)

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4226]
# Release Checklist
This checklist is for the scheduled release v1.66.0.

 **Release date:** 2021-11-11

## Pre release

- [x] Clone or update the [release toolkit](https://href.li/?https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile) and review the [release script instructions](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md).
- [x] [Notifiy open Gutenberg Mobile PRs assigned to 1.66.0 milestone](https://github.com/wordpress-mobile/gutenberg-mobile/milestone/101).
<details>
<summary>Message Template</summary>
<p>

```markdown
Hello!
We will cut the 1.66.0 release on 2021-11-11.
I plan to circle back and bump this PR to the next milestone then,
but please let me know if you’d rather us work to include this PR in 1.66.0.
Thanks!
```

</p>
</details>

- [x] Create WPiOS and WPAndroid builds from `develop`.
- [x] [Perform general writing flow tests on Android](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- [x] [Perform general writing flow tests on iOS](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Create the Release (2021-11-11)

- [x] [Verify Aztec is up to date](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md#handling-aztec-updates).
- [x] Run `./release_automation.sh` from the release toolkit to generate the main apps integration PRs.
- [x] Notify team that the release has been cut.
<details>
<summary>Message Template</summary>
<p>

```markdown
⚠️ The gutenberg-mobile 1.66.0 release branches are now cut.
Please do not merge any Gutenberg-related changes into the WPiOS or WPAndroid
develop branches until after the main apps cut their own releases next week.
If you’d like to merge changes now, merge them into the `gutenberg/after_1.66.0` branches.
```

</p>
</details>

- [x] [Verify localization string files have been generated properly](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md).
- [x] Update `Unreleased` section in [`RELEASE-NOTES.txt`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) and [`gutenberg/../CHANGELOG.md`](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/CHANGELOG.md). Add a new `Unreleased` section after updating the release notes.
- [x] Perform quick smoke test of the editor on both iOS and Android builds
- [x] Update [Gutenberg Mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pulls?q=is%3Apr+is%3Aopen+label%3Arelease-process) description. Make sure the "Changes" section informs testers on what is in the release.
- [x] Mark all 4 PRs ready for review.

## Integrate the Release

On 2021-11-11:

- [x] Verify `gutenberg` ref within the gutenberg-mobile release branch is pointing to the [latest commit](#) in Gutenberg release branch.
- [x] Create and push a `rnmobile/1.66.0` git tag for the head of [Gutenberg release branch](https://github.com/WordPress/gutenberg/branches/all?query=rnmobile%2Frelease).
- [x] [Update bundles in the Gutenberg Mobile release branch](#).
- [x] Merge **gutenberg-mobile** PR to `trunk` [using the "Create a merge commit" option](#). **WARNING** do **not** merge gutenberg PR to `trunk` yet.
- [x] Create a new Gutenberg moble release.
- [x] Update Gutenberg mobile references in the main apps.
- [x] Re-run optional tests on main apps PRs.
- [x] Merge main apps PRs to the respective `develop` branches.
- [x] Notify team that the release is now in the main apps `develop` branches
<details>
<summary>Message Template</summary>
<p>

```markdown
Hey team. I wanted to let you know that the mobile Gutenberg team has finished integrating
the 1.66.0 Gutenberg release into the WPiOS and WPAndroid `develop` branches.
The integration is ready for the next release cut/build creation when you are available.
Please let me know if you have any questions. Thanks!
```

</p>

</details>

## Sync Release

- [x] Merge release changes back to `gutenberg-mobile/develop` e.g. `trunk -> merge_release_1.66.0_to_develop -> develop`
- [x] Reslove any conflicts and merge `gutenberg/rnmobile/release_{{release_version}}` PR to `gutenberg/trunk`.
- [x] Update `gutenberg` reference in `gutenberg-mobile/merge_release_1.66.0_to_develop` to point to `gutenberg/trunk`.
- [x] Merge `gutenberg-mobile/merge_release_1.66.0_to_develop` PR to `gutenberg/develop`.

## Clean Up Pending Work

⚠️ This section may only be completed after the main apps cut their own release branches.

- [x] Open a PR to merge `gutenberg/after_1.66.0` into `gutenberg-mobile/develop`.
- [x] Merge or Close`gutenberg/after_1.66.0` **AFTER** the main apps have cut release branches.

## Test the Release

Use the main WP apps to complete the following tests:

#### iOS

- [x] Test new [changes in the release](https://github.com/wordpress-mobile/gutenberg-mobile/blob/HEAD/RELEASE-NOTES.txt).
- [x] Complete the [general writing flow tests](https://github.com/wordpress-mobile/test-cases/tree/HEAD/test-cases/gutenberg/writing-flow).
- [x] Complete the [Unsupported Block Editor test cases](https://github.com/wordpress-mobile/test-cases/blob/HEAD/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases).
- [x] Complete the [Sanity Tests](https://github.com/wordpress-mobile/test-cases/blob/HEAD/test-suites/gutenberg/sanity-test-suites.md)

#### Android

- [x] Test new [changes in the release](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt).
- [x] Complete the [general writing flow tests](https://github.com/wordpress-mobile/test-cases/tree/HEAD/test-cases/gutenberg/writing-flow).
- [x] Complete the [Unsupported Block Editor test cases](https://github.com/wordpress-mobile/test-cases/blob/HEAD/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases).
- [x] Complete the [Sanity Tests](https://href.li/?https://github.com/wordpress-mobile/test-cases/blob/HEAD/test-suites/gutenberg/sanity-test-suites.md)

## Finish the Release

- [x] Notify the next release wranglers with a **tentive schedule** for the next release.

- [x] Celebrate! 🎉

**Comment by fluiddot** [comment]
Pre release smoke testing was done in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4220 ✅ .

**Comment by fluiddot** [comment]
Issue updated:

- Added Aztec Release Checklist

**Comment by mchowning** [comment]
Would be great if the script that generates this issue could also add it to the `Mobile Gutenberg` project's "in progress" column.

**Comment by fluiddot** [comment]
> Would be great if the script that generates this issue could also add it to the `Mobile Gutenberg` project's "in progress" column.

I did a quick check on the GitHub API documentation for creating an issue ([reference](https://docs.github.com/en/rest/reference/issues#create-an-issue)) and didn't find a parameter to link it to a project, probably there's a different endpoint to achieve this 🤔 .

**Comment by mchowning** [comment]
Thanks for taking a look @fluiddot 🙇 

In theory it seems like we should be able to use the projects endpoints to accomplish this [by creating a new card](https://docs.github.com/en/rest/reference/projects#cards) that is associated to the issue. I tried testing this out, and it kept rejecting me as unauthorized even though I gave the access token pretty much every permission I have. I'm probably doing something simple wrong, but I actually feel like a GitHub action would probably be a better fit.

Anyway, this is definitely not a big deal at all, so let's not spend any more time looking into it.

Just for future reference, here are a couple of resourcesI ran across about using the rest API to assign issues to a project:
- https://stackoverflow.com/questions/57024087/github-api-how-to-move-an-issue-to-a-project
- https://blog.termian.dev/posts/project-cards-copy-github/

**Comment by jhnstn** [comment]
> I tried testing this out, and it kept rejecting me as unauthorized even though I gave the access token pretty much every permission I have.

I've been using `gh api /some/endpoint` which simplifies making authorized calls. It will prompt you to request write access if you don't have it already. 

> In theory it seems like we should be able to use the projects endpoints to accomplish this by creating a new card 

I played around with this as well but I kept running into 422 errors. I was able to create a new card on a board with api calls but when I tried adding an existing issue I would get messages like "Could not resolve to a node with the global id of ''MDU6aXNzdWUxMDUyMjE5ODIy'' . The global id is base64 hash of "05:issue{some issue id}" , not sure if `gh` is mangling the POST params or something else.

**Comment by fluiddot** [comment]
# 🟢  Test the Release - iOS

**Device:** iPhone 11 (iOS 15.1)
**Build:** 18.7.0.0

## 🟢 New changes in the release
- [x] https://github.com/wordpress-mobile/gutenberg-mobile/pull/3971
- [x] https://github.com/wordpress-mobile/gutenberg-mobile/pull/4174
- [x] https://github.com/wordpress-mobile/gutenberg-mobile/pull/4215

## 🟡  Writing Flow
#### General
- [x] TC001 - Block insertion 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
    - ⚠️ Not regression - https://github.com/WordPress/gutenberg/issues/36526
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
    - ⚠️ Not regression - https://github.com/WordPress/gutenberg/issues/36527
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

## 🟢 Unsupported Block Editing
- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

## 🟡  Sanity Tests (Test Suite 1)
### Gallery - 1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

### Gallery - 2

- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
    - ~~🔴 Not regression - **Issue:**  A **crash** is produced when uploading or retrying an upload while airplane mode is enabled (offline case).~~ Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/17488.
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3

- [x] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [TC04](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Columns - 1

- [x] Columns - Columns percentage mechanism - column's preview - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
    - ⚠️ Not regression - https://github.com/WordPress/gutenberg/issues/33601
- [x] Columns - Columns percentage mechanism - column's slider input - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)
- [x] Columns - Columns percentage mechanism - predefined percentage values are rendered correctly on frontend- [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc021)
- [x] Columns percentage mechanism - custom percentage values are rendered correctly on frontend- [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc022)
- [x] Columns - Multiple slider in columns parent - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc023)
- [x] Columns - Adding Column with AppenderButton - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)


### Columns - 2
- [x] Columns - Max limit of Column number - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
    - ⚠️ Not regression - **Issue:**  After adding more than 30 columns, the block settings gets laggy.
- [x] Columns - Min limit of Column number - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Column - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [x] Columns - Deep nesting is possible (iOS only)- [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)
    - ⚠️ Not regression - **Issue:** When nesting at 4th level a Columns block, the appender button dissapears.

### Columns - 3
- [x] Columns - Check if Column placeholders is visible for the unselected state - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [x] Columns - Mover direction - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [x] Columns - Check if Column placeholder is render in nested structure - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [x] Columns - Unselected Column placeholder is stretched to content in nested structure- [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)
    - ⚠️ Not regression - https://github.com/wordpress-mobile/gutenberg-mobile/issues/4081

### MediaText - 1

- [x] Media Text block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

### MediaText - 2

- [x] Media Text block - Insert video from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
    - ⚠️ Not regression - **Issue:** After stopping an upload and updating the post, the post gets modified and requires to be updated a second time. As far as I checked, this is caused by the `mediaId` attribute being set to `null` and removed on the first update, probably by the native side.
- [x] Media Text block - Insert image from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)
    - ~~⚠️ https://github.com/WordPress/gutenberg/issues/36529~~ Will be fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4252.

### MultipleUpload - 1

- [x] Simultaneous uploads - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)


### Cover - 1

- [x] Cover - Add image background from WordPress Media library - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
    - ⚠️ Not regression - **Issue:** The shadow of the slider's button is cut off when moved to the left side.
- [x] Cover - Image focal point is rendered properly - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [x] Cover - Custom color is rendered properly - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

### Editor Theme - 1

- [x] Default Colors - Check that default colors still load - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)
- [x] Default Gradients - Check that default gradients still load - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- [x] Custom Colors - Check that custom colors load in the editor - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)
    - ~~🔴 **Issue:** I couldn't manage to display the custom colors, it always shown the default ones.~~ Looks like this issue is coming from the  API for some specific cases, so we shouldn't consider it as a blocker for the release since it's a backend issue.

### Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)
- [x] Active icon gets product color - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc002)
- [x] Only active icons are visible when not selected - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc003)

**Comment by jhnstn** [comment]
# Test the Release - Android

**Device:** Pixel 5 (Android 12.0)
**Build:** 18.7.0.0

##  New changes in the release
- [x] https://github.com/wordpress-mobile/gutenberg-mobile/pull/3971
- [ ] https://github.com/wordpress-mobile/gutenberg-mobile/pull/4174
- [ ] ~https://github.com/wordpress-mobile/gutenberg-mobile/pull/4215~ (iOS only)

## Writing Flow
#### General
- [x] TC001 - Block insertion 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

## Unsupported Block Editing
- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [ ] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

## Sanity Tests (Test Suite 1)
### Gallery - 1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

### Gallery - 2

- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3

- [x] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [TC04](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Columns - 1

- [x] Columns - Columns percentage mechanism - column's preview - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
- [x] Columns - Columns percentage mechanism - column's slider input - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)
- [x] Columns - Columns percentage mechanism - predefined percentage values are rendered correctly on frontend- [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc021)
- [x] Columns percentage mechanism - custom percentage values are rendered correctly on frontend- [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc022)
- [x] Columns - Multiple slider in columns parent - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc023)
- [x] Columns - Adding Column with AppenderButton - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)


### Columns - 2
- [x] Columns - Max limit of Column number - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
    - ⚠️ Not regression - Issue: After adding more than 30 columns, the block settings gets laggy.
- [x] Columns - Min limit of Column number - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Column - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [ ] Columns - Deep nesting is possible (iOS only)- [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

### Columns - 3
- [x] Columns - Check if Column placeholders is visible for the unselected state - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [x] Columns - Mover direction - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [x] Columns - Check if Column placeholder is render in nested structure - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [x] Columns - Unselected Column placeholder is stretched to content in nested structure- [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

### MediaText - 1

- [x] Media Text block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

### MediaText - 2

- [x] Media Text block - Insert video from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [x] Media Text block - Insert image from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)

### MultipleUpload - 1

- [x] Simultaneous uploads - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)


### Cover - 1

- [x] Cover - Add image background from WordPress Media library - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
- [x] Cover - Image focal point is rendered properly - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [x] Cover - Custom color is rendered properly - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

### Editor Theme - 1

- [x] Default Colors - Check that default colors still load - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)
- [x] Default Gradients - Check that default gradients still load - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- [x] Custom Colors - Check that custom colors load in the editor - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)

### Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)
- [x] Active icon gets product color - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc002)
- [x] Only active icons are visible when not selected - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc003)

**Comment by fluiddot** [comment]
Release `v1.66.0` finished 🎊 !
