### ISSUE TITLE
Gallery block: Add integration tests related to its manual tests

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4532]
**Manual test reference:** 
https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md

## Tasks
1. Identify the manual test cases of the block.
1. Review all manual test cases and add them in the issue's description, which ones can be fully/partially covered by integration tests.
1. [If doesn't exist] Add a test file to the block folder.
1. Implement the test cases that can be covered by integration tests.
1. Run the test and verify that it passes.
1. Celebrate 🥳 !

### Notes
- If a test already exists in the block folder, review if the test cases can be migrated to the integration test.
- Some functionality might be not possible to replicate in the integration tests. In that case, indicate the blockers in the issue.

## Test cases
- [x] **TC001 - Close/Re-open post with an ongoing image upload**
- Can be partially tested via integration test.
- The media flow handled by the native side should be tested via end-to-end tests connected to a WordPress instance.

- [x] **~~TC002 - Close post with an ongoing image upload~~**
- Can't be tested via integration test.
- This test should be done on the native side and tested via end-to-end tests connected to a WordPress instance.

- [x] **TC003 - Add caption to gallery**
- Can be tested via integration test, although it won't be checked visually.

- [x] **TC004 - Add caption to gallery images**
- Can be tested via integration test, although it won't be checked visually.

- [x] **TC005 - Choose from device (stay in editor) - Successful upload**
- Can be partially tested via integration test.
- For testing this automatically, we would need to connect the editor to a WordPress site for double-checking that the upload was actually successful.

- [x] **TC006 - Choose from device (stay in editor) - Failed upload**
- Can be tested via integration test, although it won't be checked visually.

- [x] **TC007 - Take a photo**
- Can be partially tested via integration test.
- The native functionality of taking a photo should be tested via an end-to-end test.

- [x] **TC008 - Choose from the free photo library**
- Can be partially tested via integration test.
- The native functionality of using the free photo library should be tested via an end-to-end test.

- [x] **TC009 - Choose from device (stay in editor) - Cancel upload**
- Can be tested via integration test, although it won't be checked visually.
- For testing this automatically, we would need to connect the editor to a WordPress site for double-checking that the upload was actually canceled.

- [x] **TC010 - Rearrange images in Gallery**
- Can be tested via integration test, although it won't be checked visually.

- [x] **TC011 - Choose from Other Apps (iOS Files App)**
- Can be partially tested via integration test.
- The native functionality of using other apps should be tested via an end-to-end test.

- [x] **TC012 - Settings - Link to**
- Can be partially tested via integration test.
- With the integration test we won't cover checking visually the post/page preview.

- [x] **TC013 - Settings - Columns**
- Can be partially tested via integration test.
- We can check with the integration test if the attributes of the output HTML are expected, but we can't cover with automatic tests checking visually how the items are rendered within the editor.

- [x] **TC014 - Settings - Crop images**
- Can be partially tested via integration test.
- We can check with the integration test if the attributes of the output HTML are expected, but we can't cover with automatic tests checking visually if the images are cropped within the editor.
