### ISSUE TITLE
Mobile Gutenberg Design Audit: Pre-Beta Master Issue

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#545]
With the beta fast approaching, I am spending some time this week doing an audit of the current state of Mobile Gutenberg – primarily with a focus on UI and writing flow.

This list is broken down into categories, and will try to order based on importance in terms of user impact, but we can decide where to put them into the [Main Project](https://github.com/wordpress-mobile/gutenberg-mobile/projects/1).

* **Done**: ✅
* **In Progress**: Things that are already underway.
* **Must Have**: Things that should be included in the February Beta.
* **Nice to Have**: Things that we should _attempt to_ include in the February Beta.
* **Proposals For Future**: Things that are on my radar to improve or explore in terms of design.

## Done

- [x] Clean up styling on Inserter UI: https://github.com/wordpress-mobile/gutenberg-mobile/issues/349 (PR: #600, #608 )
- [x] Use Noto Serif everywhere: https://github.com/wordpress-mobile/gutenberg-mobile/issues/419
- [x] Pasting from top mobile editors should work well: https://github.com/wordpress-mobile/gutenberg-mobile/issues/238
- [x] Media selection and upload improvements: https://github.com/wordpress-mobile/gutenberg-mobile/issues/206
- [x] Refine inner block margins: https://github.com/wordpress-mobile/gutenberg-mobile/issues/547
- [x] Clean up styling of starter paragraph block/placeholder: https://github.com/wordpress-mobile/gutenberg-mobile/issues/549
- [x] Align text-label wording on block placeholders: https://github.com/wordpress-mobile/gutenberg-mobile/issues/592
- [x] Make entire Bottom Sheet swipeable to dismiss: https://github.com/wordpress-mobile/gutenberg-mobile/issues/596
- [x] [Android] Bottom Sheets: Inset table rows with icons to 72dp keyline: https://github.com/wordpress-mobile/gutenberg-mobile/issues/597
- [x] Inline Links UI: https://github.com/wordpress-mobile/gutenberg-mobile/pull/275 (PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/623)
- [x] Prevent focus border from shifting block contents: https://github.com/wordpress-mobile/gutenberg-mobile/issues/551 (PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/622)
- [x] Clean up styling of Title block (border, text color): https://github.com/wordpress-mobile/gutenberg-mobile/issues/540 (PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/622)
- [x] “Add new block” indicator not showing (iOS): https://github.com/wordpress-mobile/gutenberg-mobile/issues/543
- [x] Update Inserter toggle icon style: https://github.com/wordpress-mobile/gutenberg-mobile/issues/546
- [x] Tablet layout visual refinements: https://github.com/wordpress-mobile/gutenberg-mobile/issues/604
- [x] Remove all focus when tapping in empty canvas or hide keyboard button: https://github.com/wordpress-mobile/gutenberg-mobile/issues/552
- [x] Add ability to style text and add link on Image caption: https://github.com/wordpress-mobile/gutenberg-mobile/issues/574
- [x] Refine Page Break Block designs: https://github.com/wordpress-mobile/gutenberg-mobile/issues/618
- [ ] ~Add visual emphasis to focused images: https://github.com/wordpress-mobile/gutenberg-mobile/issues/601~ Being worked on in #1163 
- [ ] ~Add ability to add single new-line when typing Shift + Enter: https://github.com/wordpress-mobile/gutenberg-mobile/issues/559~

## In Progress

- [x] Refine Bottom Sheets transitions: https://github.com/wordpress-mobile/gutenberg-mobile/issues/595
- [x] Update design for Unsupported blocks: https://github.com/wordpress-mobile/gutenberg-mobile/issues/479

## Nice to Have

- [x] Add underline option to text-based blocks: https://github.com/wordpress-mobile/gutenberg-mobile/issues/562
- [ ] Improve base typographic rhythm: https://github.com/wordpress-mobile/gutenberg-mobile/issues/550

## Proposals For Future

- [ ] Add heavier weight of Noto Serif to the mix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/561
- [ ] Future proposal: Add Justify options where text-alignments are supported: https://github.com/wordpress-mobile/gutenberg-mobile/issues/575

**Comment by mchowning** [comment]
After checking with @iamthomasbishop , closing this issue (but leaving open the unfinished sub-issues) since we are past the beta release now.
