### ISSUE TITLE
Upgrade Gutenberg-Mobile to Android 13

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/gutenberg-mobile#5556]
The library will be upgraded to Android 13.

## Tasks
- [x] Upgrade `compileSdk` to 33
- [x] Upgrade `targetSdk` to 33
- [x] Bump the Aztec Editor version on [Gutenberg](https://github.com/wordpress-mobile/gutenberg-mobile/) in [#5556](https://github.com/wordpress-mobile/gutenberg-mobile/issues/5556)
- [x] Bump the Aztec Editor version on [WPAndroid](https://github.com/wordpress-mobile/WordPress-Android)
- [x] Upgrade `compileSdk` and `targetSdk` to 33 in [react-native-libraries-publisher](https://github.com/wordpress-mobile/react-native-libraries-publisher/blob/2746ac55f78dd540efb2fa8089f1e05a2f7899a0/build.gradle.kts#L25C2-L27)
- [x] Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-gesture-handler`
- [x] Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-linear-gradient`
- [x] Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-prompt-android`
- [x] Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-reanimated`
- [x] Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-slider`
- [x] Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-video`
- [x] Publish a new version
- [x] Update WPAndroid

**Comment by fluiddot** [comment]
Hey @ravishanker 👋, I see you self-assigned to this task, if you are planning to tackle this let me share the references that we'd need to update for the Android 13 upgrade. We have three libraries in the Gutenberg repository that need to be updated:

### 1 - `react-native-editor`

This is the main library that is invoked in the main apps to initialize the editor. However, part of the native code is related to [a demo project](https://github.com/WordPress/gutenberg/tree/trunk/packages/react-native-editor/android/app) that we use for testing the editor.

- [Reference to build settings](https://github.com/WordPress/gutenberg/blob/2ba91cf500d6d768d3e5d9985a0049d8cf00c2cf/packages/react-native-editor/android/build.gradle#L5-L20)

**NOTE:** Apart from updating `compileSdkVersion` and `targetSdkVersion`, it would be great to check other settings that we might also need to update for Android 13.

### 2- `react-native-bridge`

This library is where we hold the logic of the bridge between React Native and the main apps.

- [Reference to build settings](https://github.com/WordPress/gutenberg/blob/2ba91cf500d6d768d3e5d9985a0049d8cf00c2cf/packages/react-native-bridge/android/react-native-bridge/build.gradle#L17-L21)

**NOTE:** Similar to the above note, it would be great to check other settings, especially the [`WordPress-Utils-Android` dependency](https://github.com/WordPress/gutenberg/blob/2ba91cf500d6d768d3e5d9985a0049d8cf00c2cf/packages/react-native-bridge/android/react-native-bridge/build.gradle#L63).

### 3 - `react-native-aztec`

This is a wrapper library to include Aztec in the editor. If we plan to also upgrade Android 13 in [Aztec-Android](https://github.com/wordpress-mobile/AztecEditor-Android), we'd also need to bump the version [here](https://github.com/WordPress/gutenberg/blob/2ba91cf500d6d768d3e5d9985a0049d8cf00c2cf/packages/react-native-aztec/android/build.gradle#L12).

- [Reference to build settings](https://github.com/WordPress/gutenberg/blob/2ba91cf500d6d768d3e5d9985a0049d8cf00c2cf/packages/react-native-aztec/android/build.gradle#L37-L42)

**NOTE:** Similar to the above note, it would be great to check other settings, especially the [`WordPress-Utils-Android` dependency](https://github.com/WordPress/gutenberg/blob/2ba91cf500d6d768d3e5d9985a0049d8cf00c2cf/packages/react-native-aztec/android/build.gradle#L10).

**Comment by ravishanker** [comment]
👋 @fluiddot - Thank you for the note and instructions.

I've tried in vain to do this upgrade.  Looks like I need to for a few repositories and do a a lot of setup.  Still won't be sure, it's done properly.

Would it be easier for you or someone on  your team to do it quickly and easily? 🙇

**Comment by ravishanker** [comment]
Probably better to do both compileSdkVersion and targetSdkVersion at once and publish a new release that can be updated in WP repo.  Wdyt?

**Comment by ravishanker** [comment]
How does this PR relate to this work https://github.com/wordpress-mobile/AztecEditor-Android/pull/1037

**Comment by fluiddot** [comment]
Hey @ravishanker 👋 ,

> Would it be easier for you or someone on your team to do it quickly and easily? 🙇

Yeah, it's likely that someone from the GB-mobile team could take over this. Although I'm not sure about the bandwidth for this with the ongoing projects. cc @twstokes 

> Probably better to do both compileSdkVersion and targetSdkVersion at once and publish a new release that can be updated in WP repo. Wdyt?

Ok, I agree. Once we do the Android 13 upgrade in Gutenberg Mobile, we'd need to do an alpha release to incorporate the changes into the WordPress/Jetpack app.

Based on all the dependencies we need to update related to GB-mobile, I think the process should be:
1. Upgrade Android 13 in `WordPress-Utils-Android` (https://github.com/wordpress-mobile/WordPress-Utils-Android/issues/123).
2. Bump the `WordPress-Utils-Android` version in `AztecEditor-Android` ([reference](https://github.com/wordpress-mobile/AztecEditor-Android/blob/7a5afb8e715849884cb113b02beab7c6e72ef369/build.gradle#L80)).
3. Upgrade Android 13 in `AztecEditor-Android` (https://github.com/wordpress-mobile/AztecEditor-Android/pull/1037).
4. Create a new `AztecEditor-Android` version.
5. Upgrade Android 13 in Gutenberg Mobile.
6. Bump the `AztecEditor-Android` version in Gutenberg Mobile.
7. Bump the `WordPress-Utils-Android` version in Gutenberg Mobile.
8. Create a new Gutenberg Mobile release and incorporate it in `WordPress-Android`.
9. Bump the `AztecEditor-Android` version in `WordPress-Android`.
10. Bump the `WordPress-Utils-Android` version in `WordPress-Android`.

@ravishanker let me know if the above steps looks good, thanks!

> How does this PR relate to this work https://github.com/wordpress-mobile/AztecEditor-Android/pull/1037

Yes, it's definitely related, check the above steps.

**Comment by irfano** [comment]
> 1. Upgrade Android 13 in `WordPress-Utils-Android` ([Upgrade WordPress-Utils-Android to Android 13 WordPress-Utils-Android#123](https://github.com/wordpress-mobile/WordPress-Utils-Android/issues/123)).
> 2. Bump the `WordPress-Utils-Android` version in `AztecEditor-Android` ([reference](https://github.com/wordpress-mobile/AztecEditor-Android/blob/7a5afb8e715849884cb113b02beab7c6e72ef369/build.gradle#L80)).
> 3. Upgrade Android 13 in `AztecEditor-Android` ([Update compile sdk to 33 AztecEditor-Android#1037](https://github.com/wordpress-mobile/AztecEditor-Android/pull/1037)).
> 4. Create a new `AztecEditor-Android` version.
> 5. Upgrade Android 13 in Gutenberg Mobile.
> 6. Bump the `AztecEditor-Android` version in Gutenberg Mobile.
> 7. Bump the `WordPress-Utils-Android` version in Gutenberg Mobile.
> 8. Create a new Gutenberg Mobile release and incorporate it in `WordPress-Android`.
> 9. Bump the `AztecEditor-Android` version in `WordPress-Android`.
> 10. Bump the `WordPress-Utils-Android` version in `WordPress-Android`.

@fluiddot, should we update all these libraries and bump their versions in consumer projects simultaneously? For instance, can we do item 6 in a release of Gutenberg and item 7 in the next release?
Doing that seems fine to me.

**Comment by fluiddot** [comment]
> @fluiddot, should we update all these libraries and bump their versions in consumer projects simultaneously? For instance, can we do item 6 in a release of Gutenberg and item 7 in the next release?

Good question. I think the only library that we'd need to bump simultaneously is `Aztec` because it's used on both projects WP-Android (specifically for the Classic editor) and Gutenberg Mobile.

I checked the use of `WordPress-Utils-Android` library in Gutenberg Mobile ([reference](https://github.com/WordPress/gutenberg/search?q=%22org.wordpress.android.util%22)), and we only use the `AppLog` so most likely we won't have any incompatibility due to pointing to an older version.

Being this said, the main blocker I see right now is executing in the same release the points:
- 5 - Upgrade Android 13 in Gutenberg Mobile.
- 6 - Bump the AztecEditor-Android version in Gutenberg Mobile.
- 9 - Bump the AztecEditor-Android version in WordPress-Android.

> Doing that seems fine to me.

👍

**Comment by irfano** [comment]
👋🏻 @fluiddot!

> 1. Upgrade Android 13 in WordPress-Utils-Android (https://github.com/wordpress-mobile/WordPress-Utils-Android/issues/123).
> 2. Bump the WordPress-Utils-Android version in AztecEditor-Android ([reference](https://github.com/wordpress-mobile/AztecEditor-Android/blob/7a5afb8e715849884cb113b02beab7c6e72ef369/build.gradle#L80)).
> 3. Upgrade Android 13 in AztecEditor-Android (https://github.com/wordpress-mobile/AztecEditor-Android/pull/1037).
> 4. Create a new AztecEditor-Android version.
> 5. Upgrade Android 13 in Gutenberg Mobile.

Items before "5. Upgrade Android 13 in Gutenberg Mobile." are done. Can we start this issue now?

> Yeah, it's likely that someone from the GB-mobile team could take over this. Although I'm not sure about the bandwidth for this with the ongoing projects. 

Can you help us assign someone to the issue from GB-mobile team? What is the availability of the team? cc: @twstokes

**Comment by twstokes** [comment]
👋 Hey @irfano - we can prioritize this work after the completion of the VideoPress block project, which should wrap up around April 14th.

**Comment by twstokes** [comment]
Update from my side on timing: We're now aiming for May 15th due to other projects that took priority.

Ref: p1683047487883239/1683046494.190819-slack-C04T5JXRR16

**Comment by fluiddot** [comment]
Heads up that I'm going to add new tasks related to updating React Native library dependencies:
- Upgrade `compileSdk` and `targetSdk` to 33 in [react-native-libraries-publisher](https://github.com/wordpress-mobile/react-native-libraries-publisher/blob/2746ac55f78dd540efb2fa8089f1e05a2f7899a0/build.gradle.kts#L25C2-L27)
- Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-gesture-handler`
- Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-linear-gradient`
- Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-prompt-android`
- Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-reanimated`
- Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-slider`
- Upgrade `compileSdk` and `targetSdk` to 33 in `react-native-video`
