### ISSUE TITLE
Add tracking events

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#556]
There are a few things that we'll want to measure before we launch. I'm detailing here the events that we need, some will happen in the apps and some will happen in Gutenberg.

- App setting to enable Gutenberg: `gutenberg_enabled` when switched on, `gutenberg_disabled` when switched off.
- Add a `gutenberg_enabled` property to the user properties that are sent with every event.
- Add editor session events, I'll detail those separately

## Editor sessions

We want to measure whether users can successfully complete their edits with just Gutenberg. For that we'll have three events:

* `editor_session_start` when the editor is opened, with properties:
  * `editor: gutenberg | classic`
  * `content_type: new | gutenberg | classic`: `new` is for new posts, `gutenberg` is for existing posts with blocks, `classic` is for existing posts without blocks
  * `has_unsupported_blocks` for existing posts with blocks, this will be `true` if any of the blocks is unsupported
* `editor_session_switch_editor` when the user chooses to switch to the classic editor, edit the html, or go back to Gutenberg/Aztec, with property:
  * `editor: gutenberg | classic | html`
* `editor_session_end` when the editor closed, with property:
  * ~`reason`~ `outcome: cancel|discard|save|publish`: `cancel` is closing with no changes, `discard` is closing without saving changes, `save` is for saving drafts or updating existing posts, `publish` is publishing a draft

These three events would also have some common properties:

* `post_type: post | page`
* `blog_type: core | jetpack | wpcom`

## Checklist

- [x] Android: `gutenberg_setting_enabled`/`gutenberg_setting_disabled`. https://github.com/wordpress-mobile/WordPress-Android/pull/9280
- [x] Android: `gutenberg_enabled` property. https://github.com/wordpress-mobile/WordPress-Android/pull/9280
- [x] Android: Editor session events. https://github.com/wordpress-mobile/WordPress-Android/pull/9293
- [x] iOS: `gutenberg_setting_enabled`/`gutenberg_setting_disabled`. https://github.com/wordpress-mobile/WordPress-iOS/pull/11043
- [x] iOS: `gutenberg_enabled` property. https://github.com/wordpress-mobile/WordPress-iOS/pull/11043
- [x] iOS: Editor session events. https://github.com/wordpress-mobile/WordPress-iOS/pull/11040

**Comment by hypest** [comment]
> `reason: ...     discard`

BTW, I think we don't have that reason in the Android app, which by design is always letting the user come back from the editor without asking questions. The post/draft/etc is always saved in one way or the other and the user can revert the local changes later.

**Comment by koke** [comment]
Another thing to consolidate some day 😁 I think in that case, `save` seems more fitting

**Comment by koke** [comment]
All the iOS parts are in review now

**Comment by mzorz** [comment]
All the Android parts are in review now as well 👍
