### ISSUE TITLE
Implement `useSyncMedia` hook to synchronize VideoPress metadata

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#5611]
## Description

This hook handles all the metadata synchronization between the VideoPress service and the block attributes. The logic can be broken down into the following sections:

### 1 - Fetch metadata from VideoPress (VideoPress => block settings)

Using the hook [`useVideoData`](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/block-editor/hooks/use-video-data/index.ts), it makes a request to [`/videos/$guid` endpoint](https://developer.wordpress.com/docs/api/1.1/get/videos/%24guid/). if the site is private, it tries to fetch the token for the request, however, this is only needed for self-hosted sites which aren't supported yet in native.

With the metadata, it updates an internal initial state, which is used later on, and the block attributes.

### 2 - Check if the chapters file can be auto-generated

It tries to fetch the current tracks file and check if it was autogenerated. The result of this check is used later on when updating the metadata in VideoPress.

### 3 - Request video frame poster

When the post is saved, it checks if the poster is a video frame and in case the time changed, it requests a new one.

### 4 - Update metadata (Block settings => VideoPress)

When saving the post, it compares the attributes changed with the initial state and makes a POST request to VideoPress (`wpcom/v2/videopress/meta`).

The request response is used for:
- Update the initial state.
- Set the `isPrivate` attribute.
- Based on the result from point 2, generate and upload the chapters file.
- Invalidate `getEmbedPreview` resolutions based on the attributes changed. This will enforce the preview used in the player to be updated.

## Differences in the native version
- **Related to metadata update in VideoPress:** On the native version, we can't rely on the post saving to update the metadata because the editor would be closed. We'd need to use a different behavior.
- **Related to the video frame poster request:** The endpoint used is different for simple sites and other types of sites. Currently, in the native version, we don't provide information about the type of site. Hence, if we want to support this functionality we'd need to provide a workaround.
- **Related to chapter file generation:** Not sure how feasible would be to generate the file on native, it's likely that we need to delegate this to the main apps.

## Notes

- The hook can be divided into smaller hooks, we might consider this before implementing the native version.
- The WPCOM endpoints used by the hook should work in the native version for simple sites. However, for self-hosted sites, we'd need to investigate further if we need to tweak the network logic.

## Subtasks
- [ ] Divide hook into smaller hooks
- [ ] Fetch VideoPress metadata
    - [ ] Implement [`fetchVideoItem` function](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/lib/fetch-video-item/index.ts)
    - [ ] Implement [`useVideoData` hook](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/videopress/src/client/block-editor/hooks/use-video-data)
- [ ] Extract and implement [`useMediaDataUpdate` hook](https://github.com/Automattic/jetpack/blob/76104bdebaafa1a976447dd2991b1654eeb1d713/projects/packages/videopress/src/client/block-editor/hooks/use-video-data-update/index.ts#L48-L67)
- [ ] Implement [logic to update metadata VideoPress](https://github.com/Automattic/jetpack/blob/76104bdebaafa1a976447dd2991b1654eeb1d713/projects/packages/videopress/src/client/block-editor/hooks/use-video-data-update/index.ts#L370-L509) and potentially extract it to a separate hook
- [ ] Integrate hooks and the rest of the logic into the `useSyncMedia` hook

**Comment by SiobhyB** [comment]
Noting here that I have the hook working locally and am now working to organise the necessary PRs. I'm using the description at https://github.com/Automattic/jetpack/pull/29996 to outline the PRs I'm planning, and updating it as I go.
