### ISSUE TITLE
Upgrade Gradle 8.2.1 & AGP 8.0.2

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#5990]
## Description

**Internal reference:** paaHJt-57Z-p2

As part of an ongoing effort in the host apps to upgrade Gradle and AGP, we need to do the same in the Gutenberg Mobile project.

### Tasks
- [x] Upgrade Gradle and AGP in `react-native-aztec` package.
- [x] Upgrade Gradle and AGP in `react-native-bridge` package.
- [x] Upgrade Gradle and AGP in `react-native-editor` package.
- [x] Apply potential fixes derived from upgrading Gradle and AGP.
- [x] Update CI job configuration to use Java 17 in Gutenberg Mobile
- [x] Update CI job configuration to use Java 17 in Gutenberg.

### Test
- [x] Build and run the Gutenberg demo app on Android.
- [x] Check that all CI jobs succeed in Gutenberg.
- [x] Check that all CI jobs succeed in Gutenberg Mobile.
- [x] Build and run the WP-Android app using https://github.com/wordpress-mobile/WordPress-Android/pull/18775 and composite building (i.e. using local Gutenberg Mobile path).
- [x] Build and run the WP-Android app using https://github.com/wordpress-mobile/WordPress-Android/pull/18775 and published binaries of Gutenberg Mobile.
- [x] Check that all CI jobs succeed in [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android/pull/18775).
