### ISSUE TITLE
Upgrade Gutenberg-Mobile Target SDK to 34

### ISSUE THREAD

**Issue by notandyvee** [wordpress-mobile/gutenberg-mobile#6533]
## Task list
- [x] Address error `java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created` by ~~patching React Native with [this fix](https://github.com/facebook/react-native/commit/177d97d8ea962bdd4dad8fcf0efb04a307f25000)~~ upgrading React Native to version 0.71.13+ (https://github.com/WordPress/gutenberg/pull/57667)
- [x] Upgrade `targetSdk` to 34 on Gutenberg (https://github.com/WordPress/gutenberg/pull/61727)
- [x] Upgrade `targetSdk` to 34 on `AztecEditor-Android` (https://github.com/wordpress-mobile/AztecEditor-Android/issues/1072)
- [x] Bump the AztecEditor-Android version on Gutenberg
- [x] Bump the AztecEditor-Android version on WPAndroid
- [x] Upgrade `compileSdk` and `targetSdk` to 34 in [react-native-libraries-publisher](https://github.com/wordpress-mobile/react-native-libraries-publisher/blob/2746ac55f78dd540efb2fa8089f1e05a2f7899a0/build.gradle.kts#L25C2-L27) (https://github.com/wordpress-mobile/react-native-libraries-publisher/pull/31)
- [x] Upgrade `compileSdk` and `targetSdk` to 34 in `react-native-slider` (https://github.com/wordpress-mobile/react-native-slider/pull/15)
- [x] Upgrade `compileSdk` and `targetSdk` to 34 in `react-native-video` (https://github.com/wordpress-mobile/react-native-video/pull/23)
- [x] Publish a new version
- [x] Update WPAndroid

Note: I'm not certain as to the full process involved in doing that here. Will compare with the Android 13 issue - https://github.com/wordpress-mobile/gutenberg-mobile/issues/5556

**Comment by fluiddot** [comment]
Hey @notandyvee 👋 , the process to update the target SDK will be similar to the one documented in https://github.com/wordpress-mobile/gutenberg-mobile/issues/5556. The main difference is that in this case, we'll need to update fewer third-party libraries. I took the liberty to update the task list in the issue's description. Thanks 🙇 !

**Comment by notandyvee** [comment]
Thank you for confirming @fluiddot . I can use that as a checklist for understanding the process further. 🙏🏻

**Comment by fluiddot** [comment]
@notandyvee I couldn't find a branch in [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android) related to the target SDK upgrade. I'd like to test the React Native patch to address the error `java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created`. Let me know if you could share the branch, or if it's not created yet, ping me when it's ready. Thanks 🙇 !

**Comment by fluiddot** [comment]
@notandyvee I have prepared the different PRs needed for this tracking issue. The only one remaining is updating the Aztec version, however, we'd first need to tackle https://github.com/wordpress-mobile/AztecEditor-Android/issues/1072. Let me know if you are planning to work on it, in the meantime, I'm going to pause my work on this issue. Thanks 🙇 !

⚠️ I've tested WP-Android app after updating `targetSdk` in an emulator with Android 14, and noticed that the app crashes when uploading media. I thought this was related to the editor, but it can also be reproduced when uploading from the Media screen. Sharing this here so you are aware of this issue when working in https://github.com/wordpress-mobile/WordPress-Android/issues/19917.

**Comment by notandyvee** [comment]
Firstly, thank you @fluiddot for working on this so quickly. Extremely helpful 🙏🏻 .

>  I've tested WP-Android app after updating targetSdk in an emulator with Android 14, and noticed that the app crashes when uploading media.

Known issue. I have a fix locally. It's a security issue required by the target sdk update. Nothing to do with gutenberg. I'll put up a PR later today so we can use it for testing and for visibility.

> The only one remaining is updating the Aztec version, however, we'd first need to tackle https://github.com/wordpress-mobile/AztecEditor-Android/issues/1072.

I can attempt to tackle that. How are gutenberg and aztec related?

**Comment by fluiddot** [comment]
> > The only one remaining is updating the Aztec version, however, we'd first need to tackle [wordpress-mobile/AztecEditor-Android#1072](https://github.com/wordpress-mobile/AztecEditor-Android/issues/1072).
> 
> I can attempt to tackle that. How are gutenberg and aztec related?

Gutenberg Mobile uses [Aztec for rendering rich text content](https://github.com/WordPress/gutenberg/blob/8b5bc0e22480d9001d43f29b30e2c781dae8d221/packages/block-editor/src/components/rich-text/native/index.native.js#L1220-L1284). Most of the text rendered within the editor uses it.

**Comment by notandyvee** [comment]
Apologies for the delay @fluiddot . The PR with the updates to avoid image crashing are here: https://github.com/wordpress-mobile/WordPress-Android/pull/19979. I will tackle Aztec next.

**Comment by geriux** [comment]
All tasks have been completed 🚀
