### ISSUE TITLE
Include UI tests for blocks through Sample App

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/gutenberg-mobile#745]
We'll need to include an on-device testing solution to help check that everything's good to go as we make changes and include new blocks. I think once we have the following in place we'll be at a good place to start. 

## CI/CD

- [x] UI testing framework selection  #676
- [x] UI tests set to run in CI on PRs  #676

## Paragraph block

- [x] Create a short post with a single Paragraph block  #676
- [x] Create a long post with multiple Paragraph blocks #821 
- [x] Have a paragraph block with a word in it. Place the cursor in the middle of the work and tap "Enter". Verify that the block split into two paragraph blocks, each with the respective half word. #821 
- [x] Have two paragraph blocks with some content in each. Place the cursor at the beginning of the second and tap "Backspace". Verify that the blocks merged. #821 

## Image block

- [x] Create a post with a captioned Image block #1060
- [x] Create a post with a captioned Image block followed by multiple paragraph blocks #1060

## Heading block

- [x] Create a post with a heading and multiple paragraph blocks #1069 

## Inserting new blocks

- [x] Have a post with more than a few blocks. Focus the title block and insert a new block via the Inserter. Verify that the block was added at the end of the post and the view scrolled to it.(This does not happen if the post contains a heading block) #1139 
- [x] Create a post with a few blocks. Focus on the first block and insert a new block via the inserter. Verify that the block appears in its correct position in the post #1139 

I think if we can check off all of these we'll be in a good place to start here. 

--------

Additional coverage currently includes

- [x]  Copy/paste on plain and rich text content in a paragraph block
- [x] Rotating device while adding/removing blocks

**Comment by hypest** [comment]
Thanks for compiling a list @JavonDavis !

Let's add some writing flow related items. Those are actually the things that are not easy to test in Jest (no access to Aztec itself with Jest) so it's crucial to add some as baseline to build the testsuite on.

For example:
- [ ] Have a paragraph block with a word in it. Place the cursor in the middle of the work and tap "Enter". Verify that the block split in two paragraph blocks, each with the respective half word.
- [ ] Have two paragraph blocks with some content in each. Place the cursor at the beginning of the second and tap "Backspace". Verify that the blocks merged.
- [ ] Have a post with more than a few blocks. Focus the title block and insert a new block via the Inserter. Verify that the block was added at the end of the post and the view scrolled to it.

What do you think?

**Comment by JavonDavis** [comment]
> Let's add some writing flow related items. Those are actually the things that are not easy to test in Jest (no access to Aztec itself with no device Jest tests) so it's crucial to add some as baseline to build the testsuite on.

Ahh I see, makes sense! 

> What do you think?

I think the idea behind it is totally correct, it's going to take a little more effort technically to accomplish certain actions though, I'll start looking into it. I'll try and rethink the list to cover the ones you mentioned and more of these sort of writing flows alongside the simple ones I included.

**Comment by JavonDavis** [comment]
@hypest I'll also mention that this list was just a starting point to build upon, I mainly wanted to have a good base on the code for interacting with all the blocks to see what's possible(reliably) and what's not and then build on from there. Thanks for mentioning the flows because now I'm thinking to just expand this issue to also include items covering those areas to have an idea what interactions we'll need to keep in mind, I'll organize the description into sections and then we can build on a few more flows to have an idea of where we want to be. Does that sound good?

**Comment by hypest** [comment]
Sounds awesome @JavonDavis . The starting point is good anyway, it's just that I think with on-device testing, it will actually have higher immediate value if we test a couple of flow-related cases instead of going broad (e.g testing all available blocks). We will eventually want to test everything, but to start it's better to focus on flows. 👍

**Comment by hypest** [comment]
Can we add a task to write a small guide on how to write a new UI (Appium) test? That would help people start adding tests on their own. Thanks!

**Comment by JavonDavis** [comment]
> Can we add a task to write a small guide on how to write a new UI (Appium) test? That would help people start adding tests on their own. Thanks!

Yeah I already started on a separate README file for this, I'll finish this up once we resolve the issues with the merge.

**Comment by hypest** [comment]
👋 @JavonDavis , I'm thinking, what do you think about adding the following test cases too? For some, my rationale is to help us get some tests in place that exercise our ability to actually test them. Only one test in any of those should be enough to lay the foundation.

* Test that tapping Enter at the end of a Heading block creates a _normal_ paragraph block beneath it
* Include one pasting related test. The simplest could be to paste a two-paragraph text snippet and see that we get two paragraph blocks created.
* Include one device rotation test

**Comment by JavonDavis** [comment]
> my rationale is to help us get some tests in place that exercise our ability to actually test them. 

@hypest yeah totally but isn't that the case for what's currently there now? and this is would be the aim for all the tests?

The additions you propose sound good! 👍 Could you just clarify what would be the goal for the device rotation test? Just checking that rotating 90 then -90 doesn't break anything?

**Comment by JavonDavis** [comment]
> Yeah I already started on a separate README file for this, I'll finish this up once we resolve the issues with the merge.

As previously mentioned I went the route of adding additional information to the project Wiki which is there now 😄 I'll continue to improve it as we build this out some more and point to it in the project README

**Comment by mchowning** [comment]
> I went the route of adding additional information to the project Wiki which is there now 😄

Nice! 👍  

It might be worth adding a link to that in the [UI Tests](https://github.com/wordpress-mobile/gutenberg-mobile#ui-tests) section of the Readme that you added so it's easy to find. Hypothetically speaking, someone who was looking at the UI tests recently might have read the Readme section but not realized there was a Wiki page regarding the UI tests (this person 100%, most definitely was not me 😁).

**Comment by hypest** [comment]
> >  my rationale is to help us get some tests in place that exercise our ability to actually test them.
>
> @hypest yeah totally but isn't that the case for what's currently there now? and this would be the aim for all the tests?

👋 @JavonDavis , yeap, that's the case, although notice that I was referring as "For some (of the proposed additions)". Sorry it wasn't clear but, I was mainly referring to the pasting and rotation tests for which we don't have the helper methods in place yet to perform. The goal will be to have the helper functions in place so we use them in future tests. Not sure if it's trivial to perform those operations in Appium as is already.

>The additions you propose sound good! 👍 Could you just clarify what would be the goal for the device rotation test? Just checking that rotating 90 then -90 doesn't break anything?

Main goal with that one is to be able to have the rotation feature being performed by the automated test. It would then be super useful to use in other tests, where we will be testing out that things continue to look good, that content is preserved, layout is adjusted and generally, whatever test we can think of. But for the scope of this proposal, we'd only need to do the rotation and test something easy/trivial (block content could be it). Let me know if this clears things up, happy to expand!

**Comment by JavonDavis** [comment]
@hypest just a heads up that the PRs for the remaining tasks on this list are ready, I'm going to spend some time working with James on reducing the time they take to execute and stability

**Comment by rachelmcr** [comment]
@JavonDavis I see that all the tasks in the issue description are complete. Can we close this issue? If there is any incomplete work here, perhaps we can move it to a new issue for followup.

**Comment by JavonDavis** [comment]
@rachelmcr thanks for the ping on this, closing this since the work on this master issue is complete
