### ISSUE TITLE
Convert BlockManager into BlockList

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#958]
In [previous](https://github.com/wordpress-mobile/gutenberg-mobile/pull/789) [efforts](https://github.com/WordPress/gutenberg/pull/14662) we tried to port the [BlockManager](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-manager.js) and related components from the [Gutenberg mobile repository](https://github.com/wordpress-mobile/gutenberg-mobile) to the Gutenberg repository, to pave the way for inner blocks on RN mobile. However that prove to be unsuccessful as the PR was getting too big to review at once.

To give more context, `BlockManager` is the equivalent of `BlockList` and it depends on many components that still lives in the gutenberg-mobile repo.
The goal here will be to make that port so that we can ultimately have BlockList be reused from the gutenberg repository in components such as `InnerBlock`.

This issue will serve as a reference for this task and will help monitor the progress on the different PRs.

Most of the work was already done in #789, but we're going to break it down now into smaller pieces to make it easier to review.

Suggested plan:

- [x] 1. Move `BottomSheet` and `Picker` to `@wordpress/components` make them available from outside the `block-editor` package (GB [PR#15750](https://github.com/WordPress/gutenberg/pull/15750) and GB-Mobile [PR#1008](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1008))
- [x] 2. Port `KeyboardAvoidingView`, `KeyboardAwareFlatList` and `ReadableContentView` to gutenberg so we can reuse those from there (GB [PR#15913](https://github.com/WordPress/gutenberg/pull/15913) and GB-Mobile [PR#1048](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1048))
- [x] 3. `Inserter` ported from [`BlockPicker`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-picker.js) (GB [PR#16114](https://github.com/WordPress/gutenberg/pull/16114) and GB-Mobile [PR#1122](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1122))
- [x] 4. `BlockMobileToolbar` ported from [`InlineToolbar`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/inline-toolbar/index.js) (GB [PR#16177](https://github.com/WordPress/gutenberg/pull/16177) and GB-Mobile [PR#1133](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1133))
- [x] 5. `BlockToolbar` ported from [`BlockToolbar`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-toolbar.js) (GB [PR#16213](https://github.com/WordPress/gutenberg/pull/16213) and GB-Mobile [PR#1149](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1149))
- [x] 6. `BlockListBlock` ported from [`BlockHolder`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-holder.js) (GB [PR#16223](https://github.com/WordPress/gutenberg/pull/16223) and GB-Mobile [PR#1155](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1155))
- [x] 7. `HTMLTextInput` ported from [`HTMLTextInput`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/components/) (GB [PR#16226](https://github.com/WordPress/gutenberg/pull/16226) and GB-Mobile [PR#1162](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1162))
- [x] 8. `BlockList` ported from [`BlockManager`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/src/block-management/block-manager.js) (GB [PR#16239](https://github.com/WordPress/gutenberg/pull/16239) and GB-Mobile [PR#1169](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1169))
- [x] 8b. Port `MainScreen`, `AppContainer` and `App` to gutenberg  (GB [PR#16260](https://github.com/WordPress/gutenberg/pull/16260) and GB-Mobile [PR#1171](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1171))
- [x] 9. Create a native version of `InnerBlock` by adding support for `MediaText` (GB [PR#16305](https://github.com/WordPress/gutenberg/pull/16305))

_Originally posted in https://github.com/wordpress-mobile/gutenberg-mobile/pull/789#issuecomment-489067001_

cc @koke @hypest @daniloercoli @gziolo

**Comment by koke** [comment]
Removing my assignment for now. @Tug will take over this, and I'll help where I can.
